title: A curious blog
description: For other curious, who wants to learn more about basics of computer science. Because computer science, it's cool !
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
name: Loïc Tetrel
repository: ltetrel/ltetrel.github.io
